### ISSUE TITLE
Masalah ukuran layar

### ISSUE THREAD

**Issue by Fadimhats1** [CharlesKristov/LaForant#5]
## Kondisi di zoom 100%:
![image](https://user-images.githubusercontent.com/73393838/118870989-55343700-b911-11eb-980a-291b3e2cd24a.png)

## Kondisi di zoom 80%:
![image](https://user-images.githubusercontent.com/73393838/118871049-654c1680-b911-11eb-8f65-52d275aea6c2.png)
@randyyz

**Comment by randyyz** [comment]
sdh kuubah.. fixed?
todo:
- triangle yg di header
- backround
